apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      containers:
      - name: ml-model-container
        image: sonvu2004/ml-model:latest
        ports:
        - containerPort: 80
